<div class="tcb-bn-responsive mt-10"></div>

<div class="tcb-bn-autoplay"></div>

<div id="tcb-autoplay-message">
	<p class="info-text">
	<?php echo __( 'Autoplay is not currently supported by default on mobile devices (tablets, phones). Autoplay will also be muted by default on Chrome and Safari', 'thrive-cb' ) ?>
	</p>
</div>

<div class="tcb-bn-preload"></div>

<div class="tcb-bn-loop"></div>

<div class="tcb-bn-muted"></div>

<div class="tcb-bn-lazy_load tcb-disabled"></div>
