<div class="tvd-header">
    <nav id="tvd-nav">
        <div class="nav-wrapper">
            <div class="tve-logo tvd-left">
                <a href="<?php menu_page_url( 'tve_dash_section' ); ?>"
                   class="tvd-users-dashboard-logo"
                   title="<?php echo __( 'Thrive Dashboard', 'thrive-dash' ) ?>">
                            <span class="tvd-logo-container">
                                <img class="thrive_admin_logo"
                                     src="<?php echo TVE_DASH_URL ?>/css/images/thrive-logo.png"
                                     alt="">
                            </span>
                </a>
            </div>
            <ul id="tvd-dash-submenu" class="tvd-right">
				<?php do_action( 'tvd_notification_inbox' ); ?>
                <li>
                    <a id="tvd-support-token" href="javascript:void(0)" class=" tvd-btn tvd-btn-green tvd-full-btn dashtoken">
						<?php _e( 'Support login', 'thrive-dash' ); ?>
                    </a>
                </li>

            </ul>
        </div>
    </nav>
</div>

<div class="td-app-notification-overlay overlay close"></div>
<div class="td-app-notification-drawer">
    <div class="td-app-notification-holder">
        <div class="td-app-notification-header notification-header-notify-td"></div>
        <div class="td-app-notification-wrapper notification-wrapper-notify-td"></div>
        <div class="notification-footer notification-footer-notify-td"></div>
    </div>
</div>
<?php include TVE_DASH_PATH . '/templates/share.phtml'; ?>
