<div class="drop-panel panel-light panel-tooltip sp-panel">
	<div class="tve-tooltip-close"><span class="click" data-fn="onCancel"><?php tcb_icon( 'exit' ) ?></span></div>
	<div class="tve-tooltip-content popup-content"></div>
	<div class="tve-sp-action">
		<a class="tve-button green click learn_more_link" href="" target="_blank" data-fn="onApply">
			<?php echo __( 'Learn More', 'thrive-cb' ); ?>
		</a>
	</div>
	<div class="tcb-panel-arrow tve-top-drop-panel"></div>
</div>
