<div class="tcb-row tve-webhook-header-row">
	<input type="text" class="tve-webhook-header-key" placeholder="Key" />
    <span class="tve-webhook-header-operator">=</span>
	<span class="tve-webhook-picker-wrap">
		<input type="text" class="tve-webhook-header-value" placeholder="Value" />
		<button type="button" class="tve-webhook-value-picker-btn" title="Insert dynamic value">
			<svg class="tcb-icon tcb-icon-database-light"><use xlink:href="#icon-database-light"></use></svg>
		</button>
		<div class="tve-webhook-picker-dropdown tcb-card tcb-hide"></div>
	</span>
	<a href="#" class="tve-webhook-header-remove">
		<svg class="tcb-icon tcb-icon-trash-light"><use xlink:href="#icon-trash-light"></use></svg>
	</a>
</div>
