<div class="tve_lg_regular_input tve_lg_input tve_lg_input_container tve_lg_date tve-lg-show-counter tcb-plain-text tcb-lg-date">
	<input
		name="date-field"
		type="text"
		class="tcb-plain-text lg-date-picker"
		readonly="readonly"
		data-picker-type="date"
		data-display-type="modal"
		data-date-format="m-d-Y"
		data-is-futuristic-date="0"
		data-time-interval-type="first-interval" /></div>
</div>