<div class="control-grid full-width pb-0">
	<p class="m-0">
		<?php echo __( 'Our Zapier integration now supports custom fields!', 'thrive-cb' ); ?>
	</p>
	<a class="blue-text mt-10" href="https://thrivethemes.com/tkb_item/what-autoresponders-does-the-custom-field-integration-with-the-lead-generation-element-support/#list" target="_blank">
		<?php echo __( 'Learn more now', 'thrive-cb' ) ?>
	</a>
</div>