<div class="tcb-custom-url-with-target">
    <div class="tcb-link-search-slot"></div>
    <div class="tcb-link-target mt-10">
        <label class="tcb-checkbox tcb-link-newtab">
            <input type="checkbox" class="tve-checkbox tcb-link-target-newtab">
            <span class="grey-text"><?php esc_html_e( 'Open in new tab', 'thrive-cb' ); ?></span>
        </label>
    </div>
    <div class="tcb-send-params mt-10">
        <label class="tcb-checkbox tcb-send-params-checkbox">
            <input type="checkbox" class="tve-checkbox tcb-send-params-input">
            <span class="grey-text"><?php esc_html_e( 'Send form values to thank you page', 'thrive-cb' ); ?></span>
        </label>
        <a class="click blue-text center-text tcb-hidden view-params" data-fn="showSentParams"><?php esc_html_e( 'View variable details', 'thrive-cb' ); ?></a>
    </div>
</div>
