<div class="pt-5">
	<?php echo esc_html_e( 'Post text:', 'thrive-cb' ) ?>
	<textarea rows="3" data-setting="post" class="keyup post" data-fn="char_count"><#=this.data.post#></textarea>
	<div class="row middle-xs">
		<div class="col-xs-9">
			<div class="bluesky-message inline-message" style="padding:0"></div>
		</div>
		<div class="col-xs-3">
			<div id="bluesky-counter" class="tcb-text-right"></div>
		</div>
	</div>
</div>
