<div class="pt-5">
	<?php echo __( 'Post text:', 'thrive-cb' ) ?>
	<textarea rows="3" data-setting="post" class="keyup post" data-fn="char_count"><#=this.data.post#></textarea>
	<div class="row middle-xs">
		<div class="col-xs-9">
			<div class="x-message inline-message" style="padding:0"></div>
		</div>
		<div class="col-xs-3">
			<div id="x-counter" class="tcb-text-right"></div>
		</div>
	</div>
</div>
<div class="pt-10">
	<div class="row middle-xs">
		<div class="col-xs-1">
			via:
		</div>
		<div class="col-xs-1" style="padding-left:.8rem">@</div>
		<div class="col-xs-10">
			<input data-setting="via" class="keyup via" data-fn="char_count" value="<#=this.data.via#>">
		</div>
	</div>
</div>
